# Generated by Django 2.0.1 on 2018-06-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_auto_20180615_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='date',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
