# Generated by Django 2.0.1 on 2018-06-15 17:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0011_auto_20180615_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='date',
            field=models.DateTimeField(default=datetime.date(2018, 6, 15), max_length=12, null=True),
        ),
    ]
