# Generated by Django 2.0.1 on 2018-06-15 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0012_auto_20180615_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='date',
            field=models.DateTimeField(default='2018-06-15', max_length=12, null=True),
        ),
    ]
