# Generated by Django 2.0.1 on 2018-06-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0013_auto_20180615_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='date',
            field=models.DateField(default='2018-06-15', max_length=12, null=True),
        ),
    ]
