# Generated by Django 2.0.1 on 2018-06-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0014_auto_20180615_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='value',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='date',
            field=models.DateField(default='2018-06-16', max_length=12, null=True),
        ),
    ]
